name: ticktick_dbt

profile: ticktick_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  airbyte_meta_fields:
    - '_airbyte_raw_id'
    - '_airbyte_extracted_at'
    - '_airbyte_meta'
    - '_airbyte_generation_id'

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  ticktick_dbt:
    +schema: raw

models:
  ticktick_dbt:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true