name: life_admin_dbt

profile: life_admin_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  airbyte_meta_fields:
    - '_airbyte_raw_id'
    - '_airbyte_extracted_at'
    - '_airbyte_meta'
    - '_airbyte_generation_id'

  enable_gtd_work_type_categorization: "{{ env_var('ENABLE_GTD_WORK_TYPE_CATEGORIZATION', 'false') | as_bool }}"
  gtd_deep_work_tags: "{{ env_var('GTD_DEEP_WORK_TAGS', '[]') }}"
  gtd_shallow_work_tags: "{{ env_var('GTD_SHALLOW_WORK_TAGS', '[]') }}"
  timezone: "{{ env_var('DBT_TIMEZONE', 'UTC') }}"
  # the pipeline load interval in minutes 
  load_interval: "{{ env_var('DBT_LOAD_INTERVAL', '15') | as_number }}"
  dbt-osmosis:
    sources:
      ticktick_raw:
        path: staging/ticktick/source_{node.source_name}.yml
        schema: ticktick_raw


exposures: 
  +enabled: "{{ target.name != 'load_raw' }}"


sources: 
  life_admin_dbt:
    +enabled: "{{ target.name != 'load_raw' }}"
    raw:
      +enabled: "{{ target.name == 'load_raw' }}"
      external_table_stage:
        +enabled: "{{ target.name == 'stage_raw' }}"

models:
  life_admin_dbt:
    +enabled: "{{ target.name != 'load_raw' }}"
    +dbt-osmosis-options:
      force-inherit-descriptions: true
      sort-by: "alphabetical"
    staging:
      +materialized: view
      +dbt-osmosis: "{parent}.yml"
    marts:
      +materialized: view
      +dbt-osmosis: "{parent}.yml"
    raw:
      +enabled: "{{ target.name == 'load_raw' }}"
      todoist:
        +tags: "todoist"
        +materialized: external
        +format: json
  # elementary:
  #   +schema: elementary
  #   enabled: "{{ target.name == 'prod' }}"
flags:
  require_generic_test_arguments_property: true
  require_explicit_package_overrides_for_builtin_materializations: false