version: 2
models:
  - name: base__ticktick__tasks
    description: |
      - base table containing latest task state pulled from ticktick open API
      - source : https://developer.ticktick.com/api#/openapi?id=task-1
    columns:
      - name: _completed_time
        data_type: datetime
        description: |
          - Task completed time in "yyyy-MM-dd'T'HH:mm:ssZ"
          - Is not useful so kept internally for reference only.
          - Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: childids
        data_type: array<string>
        description: list of subtasks
        config:
          meta: {}
          tags: []
      - name: column_id
        data_type: string
        config:
          meta: {}
          tags: []
      - name: due_date
        data_type: datetime
        description: |
          - Task due date time in "yyyy-MM-dd'T'HH:mm:ssZ"
          - Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: etag
        data_type: string
        description: ephemeral slug generated by ticktick. Not useful for analytics.
        config:
          meta: {}
          tags: []
      - name: is_allday
        data_type: boolean
        description: All day
        config:
          meta: {}
          tags: []
      - name: kind
        data_type: string
        description: '"TASK" or "NOTE"'
        config:
          meta: {}
          tags: []
      - name: parent_id
        data_type: string
        description: Parent task id
        config:
          meta: {}
          tags: []
      - name: priority
        data_type: int64
        description: 'Task priority. Value : None:0, Low:1, Medium:3, High5'
        config:
          meta: {}
          tags: []
      - name: project_id
        data_type: string
        description: Task project id
        config:
          meta: {}
          tags: []
      - name: reminders
        data_type: array<string>
        description: List of reminder triggers. Example [ "TRIGGER:P0DT9H0M0S", "TRIGGER:PT0S" ]
        config:
          meta: {}
          tags: []
      - name: repeat_flag
        data_type: string
        description: |
          Recurring rules of task.
          - Example : "RRULE:FREQ=DAILY;INTERVAL=1"
        config:
          meta: {}
          tags: []
      - name: sort_order
        data_type: int64
        description: Task sort order
        config:
          meta: {}
          tags: []
      - name: start_date
        data_type: datetime
        description: |
          - Start date time in "yyyy-MM-dd'T'HH:mm:ssZ". 
          - Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: status
        data_type: int64
        description: 'Task completion status. Value : Normal: 0, Completed: 2'
        config:
          meta: {}
          tags: []
      - name: tags
        description: Array of tags assigned to the task.
        config:
          meta: {}
          tags: []
        data_type: ARRAY<STRING>
      - name: task_id
        data_type: string
        description: Task identifier
        config:
          meta: {}
          tags: []
      - name: timezone
        data_type: string
        description: Task timezone
        config:
          meta: {}
          tags: []
      - name: title
        data_type: string
        description: Task title
        config:
          meta: {}
          tags: []
  - name: base__ticktick__tasks_snapshot
    description: >-
      tasks snapshot that gets loaded on short interval to capture completed / deleted tasks
    columns:
      - name: _completed_time
        data_type: datetime
        description: |
          - Task completed time in "yyyy-MM-dd'T'HH:mm:ssZ"
          - Is not useful so kept internally for reference only.
          - Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: childids
        data_type: array<string>
        description: list of subtasks
        config:
          meta: {}
          tags: []
      - name: column_id
        data_type: string
        config:
          meta: {}
          tags: []
      - name: dbt_scd_id
        data_type: string
        description: >-
          A unique key generated for each snapshot row. Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: dbt_updated_at
        data_type: datetime
        description: >-
          The updated_at timestamp of the source record when this snapshot row was inserted. Timezone
          conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: dbt_valid_from
        data_type: datetime
        description: >-
          The timestamp when this snapshot row was first inserted and became valid. Timezone conversion
          available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: dbt_valid_to
        data_type: datetime
        description: >-
          The timestamp when this row became invalidated. For current records, this is NULL by default
          or the value specified in dbt_valid_to_current. Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: due_date
        data_type: datetime
        description: |
          - Task due date time in "yyyy-MM-dd'T'HH:mm:ssZ"
          - Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: etag
        data_type: string
        description: ephemeral slug generated by ticktick. Not useful for analytics.
        config:
          meta: {}
          tags: []
      - name: is_allday
        data_type: boolean
        description: All day
        config:
          meta: {}
          tags: []
      - name: kind
        data_type: string
        description: '"TASK" or "NOTE"'
        config:
          meta: {}
          tags: []
      - name: parent_id
        data_type: string
        description: Parent task id
        config:
          meta: {}
          tags: []
      - name: priority
        data_type: int64
        description: 'Task priority. Value : None:0, Low:1, Medium:3, High5'
        config:
          meta: {}
          tags: []
      - name: project_id
        data_type: string
        description: Task project id
        config:
          meta: {}
          tags: []
      - name: reminders
        data_type: array<string>
        description: List of reminder triggers. Example [ "TRIGGER:P0DT9H0M0S", "TRIGGER:PT0S" ]
        config:
          meta: {}
          tags: []
      - name: repeat_flag
        data_type: string
        description: |
          Recurring rules of task.
          - Example : "RRULE:FREQ=DAILY;INTERVAL=1"
        config:
          meta: {}
          tags: []
      - name: sort_order
        data_type: int64
        description: Task sort order
        config:
          meta: {}
          tags: []
      - name: start_date
        data_type: datetime
        description: |
          - Start date time in "yyyy-MM-dd'T'HH:mm:ssZ". 
          - Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: status
        data_type: int64
        description: 'Task completion status. Value : Normal: 0, Completed: 2'
        config:
          meta: {}
          tags: []
      - name: tags
        description: Array of tags assigned to the task.
        config:
          meta: {}
          tags: []
        data_type: ARRAY<STRING>
      - name: task_id
        data_type: string
        description: Task identifier
        config:
          meta: {}
          tags: []
      - name: timezone
        data_type: string
        description: Task timezone
        config:
          meta: {}
          tags: []
      - name: title
        data_type: string
        description: Task title
        config:
          meta: {}
          tags: []
  - name: base__ticktick__projects
    description: |
      - Base table containing latest project state pulled from ticktick open API
      - Source : https://developer.ticktick.com/api#/openapi?id=project-1
    columns:
      - name: closed
        data_type: boolean
        description: Project closed
        config:
          meta: {}
          tags: []
      - name: color
        data_type: string
        description: Project color
        config:
          meta: {}
          tags: []
      - name: group_id
        data_type: string
        description: Project group identifier
        config:
          meta: {}
          tags: []
      - name: kind
        data_type: string
        description: "\"TASK\" or \"NOTE\"\n"
        config:
          meta: {}
          tags: []
      - name: permission
        data_type: string
        description: '"read", "write" or "comment"'
        config:
          meta: {}
          tags: []
      - name: project_id
        data_type: string
        description: Project identifier
        config:
          meta: {}
          tags: []
      - name: project_name
        data_type: string
        description: Project name
        config:
          meta: {}
          tags: []
      - name: sort_order
        data_type: int64
        description: Order value
        config:
          meta: {}
          tags: []
      - name: view_mode
        data_type: string
        description: view mode, "list", "kanban", "timeline"
        config:
          meta: {}
          tags: []
  - name: base__ticktick__projects_snapshot
    description: >-
      project snapshot that gets loaded on short interval to capture completed / deleted projects
    columns:
      - name: closed
        data_type: boolean
        description: Project closed
        config:
          meta: {}
          tags: []
      - name: color
        data_type: string
        description: Project color
        config:
          meta: {}
          tags: []
      - name: dbt_scd_id
        data_type: string
        description: >-
          A unique key generated for each snapshot row. Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: dbt_updated_at
        data_type: datetime
        description: >-
          The updated_at timestamp of the source record when this snapshot row was inserted. Timezone
          conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: dbt_valid_from
        data_type: datetime
        description: >-
          The timestamp when this snapshot row was first inserted and became valid. Timezone conversion
          available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: dbt_valid_to
        data_type: datetime
        description: >-
          The timestamp when this row became invalidated. For current records, this is NULL by default
          or the value specified in dbt_valid_to_current. Timezone conversion available with env var DBT_TIMEZONE
        config:
          meta: {}
          tags: []
      - name: group_id
        data_type: string
        description: Project group identifier
        config:
          meta: {}
          tags: []
      - name: kind
        data_type: string
        description: "\"TASK\" or \"NOTE\"\n"
        config:
          meta: {}
          tags: []
      - name: permission
        data_type: string
        description: '"read", "write" or "comment"'
        config:
          meta: {}
          tags: []
      - name: project_id
        data_type: string
        description: Project identifier
        config:
          meta: {}
          tags: []
      - name: project_name
        data_type: string
        description: Project name
        config:
          meta: {}
          tags: []
      - name: sort_order
        data_type: int64
        description: Order value
        config:
          meta: {}
          tags: []
      - name: view_mode
        data_type: string
        description: view mode, "list", "kanban", "timeline"
        config:
          meta: {}
          tags: []

  - name: base__ticktick_v3__tasks
    description: >-
      v3 base task replica with strict typing plus legacy-compatible fields extracted from raw_json
    columns:
      - name: task_id
        data_type: string
        description: Task identifier
      - name: account_id
        data_type: string
        description: TickTick account identifier
      - name: project_id
        data_type: string
        description: Project identifier
      - name: sort_order
        data_type: int64
        description: Task ordering value from v3 payload
      - name: title
        data_type: string
        description: Task title
      - name: content
        data_type: string
        description: Task note or description body
      - name: timezone
        data_type: string
        description: IANA timezone parsed from raw_json
      - name: is_allday
        data_type: boolean
        description: All-day flag parsed from raw_json
      - name: priority
        data_type: int64
        description: Task priority value
      - name: status
        data_type: int64
        description: Task status code
      - name: deleted
        data_type: int64
        description: Soft-delete marker from replica
      - name: column_id
        data_type: string
        description: TickTick column identifier
      - name: etag
        data_type: string
        description: ETag for optimistic concurrency
      - name: kind
        data_type: string
        description: Task kind
      - name: repeat_flag
        data_type: string
        description: Repeat rule from raw_json
      - name: start_date
        data_type: datetime
        description: Start date normalized to DBT timezone
      - name: due_date
        data_type: datetime
        description: Due date normalized to DBT timezone
      - name: _completed_time
        data_type: datetime
        description: Completion timestamp normalized to DBT timezone
      - name: completed_user_id
        data_type: string
        description: User ID that completed the task
      - name: created_time
        data_type: datetime
        description: Creation timestamp normalized to DBT timezone
      - name: modified_time
        data_type: datetime
        description: Last modified timestamp normalized to DBT timezone
      - name: updated_at
        data_type: datetime
        description: Replica update timestamp normalized to DBT timezone
      - name: parent_id
        data_type: string
        description: Parent task identifier
      - name: tags
        data_type: array<string>
        description: Tag list parsed from raw_json
      - name: childids
        data_type: array<string>
        description: Child task identifiers parsed from raw_json
      - name: reminders
        data_type: array<string>
        description: Reminder values parsed from raw_json
      - name: raw_json
        data_type: string
        description: Original v3 payload for forward-compatible extraction

  - name: base__ticktick_v3__projects
    description: >-
      v3 base project replica with typed fields and legacy compatibility fields extracted from raw_json
    columns:
      - name: project_id
        data_type: string
        description: Project identifier
      - name: account_id
        data_type: string
        description: TickTick account identifier
      - name: project_name
        data_type: string
        description: Project name
      - name: sort_order
        data_type: int64
        description: Project ordering value
      - name: group_id
        data_type: string
        description: Group identifier
      - name: kind
        data_type: string
        description: Project kind
      - name: color
        data_type: string
        description: Project color extracted from raw_json
      - name: view_mode
        data_type: string
        description: Project view mode
      - name: permission
        data_type: string
        description: Project permission extracted from raw_json
      - name: closed
        data_type: boolean
        description: Project closed state
      - name: etag
        data_type: string
        description: ETag for optimistic concurrency
      - name: modified_time
        data_type: datetime
        description: Last modified timestamp normalized to DBT timezone
      - name: updated_at
        data_type: datetime
        description: Replica update timestamp normalized to DBT timezone
      - name: raw_json
        data_type: string
        description: Original v3 payload for forward-compatible extraction

  - name: base__ticktick_v3__groups
    description: >-
      v3 base project-group replica used for folder-level context in downstream v3 staging
    columns:
      - name: group_id
        data_type: string
        description: Group identifier
      - name: account_id
        data_type: string
        description: TickTick account identifier
      - name: group_name
        data_type: string
        description: Group name
      - name: deleted
        data_type: boolean
        description: Group deleted state
      - name: sort_order
        data_type: int64
        description: Group ordering value
      - name: sort_type
        data_type: string
        description: Group sort type
      - name: view_mode
        data_type: string
        description: Group view mode extracted from raw_json
      - name: etag
        data_type: string
        description: ETag for optimistic concurrency
      - name: updated_at
        data_type: datetime
        description: Replica update timestamp normalized to DBT timezone
      - name: raw_json
        data_type: string
        description: Original v3 payload for forward-compatible extraction