# .github/workflows/dbt_run.yml
name: Run dbt Snapshot

on:

  workflow_dispatch:

  repository_dispatch:
    types: [airbyte_sync_completed]

jobs:
  run-dbt-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dbt project
        uses: actions/checkout@v4
        
      - name: Run dbt snapshot with DuckDB 🦆
        uses: luutuankiet/dbt-action@v1.1.1
        with:
          # This pulls a docker image pre-loaded with dbt and duckdb
          dbt_command: "dbt build"
        env:
          DBT_PROFILES_DIR: .
          GCS_KEY: ${{ secrets.GCS_KEY }}
          GCS_SECRET: ${{ secrets.GCS_SECRET }}
          DBT_TARGET: "snapshot"